--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/David-pm-pl/BanItem-PM4
build-by-default: true
branches:
- master
projects:
  BanItem-PM4:
    path: ""
    model: default
    icon: banitem.png
...
